<?php

use App\Audit\Presentation\AuditController;
use App\Identity\Domain\Role;
use App\Identity\Presentation\AuthController;
use App\Identity\Presentation\UserController;
use App\Sales\Presentation\ActivityController;
use App\Sales\Presentation\ArchiveController;
use App\Sales\Presentation\CustomerController;
use App\Sales\Presentation\DashboardController;
use App\Sales\Presentation\DealController;
use App\Sales\Presentation\ExportController;
use App\Sales\Presentation\FollowUpController;
use App\Sales\Presentation\ImportController;
use App\Sales\Presentation\MasterController;
use App\Sales\Presentation\PipelineController;
use App\Sales\Presentation\ProspectController;
use App\Sales\Presentation\TargetController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::get('health', fn () => ['status' => 'ok']);
    Route::get('ready', function () {
        DB::select('SELECT 1');

        return ['status' => 'ready'];
    });
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login')->name('auth.login');
    Route::middleware(['auth:sanctum', 'active'])->group(function () {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::post('auth/revoke-all', [AuthController::class, 'revokeAll']);
        Route::get('users', [UserController::class, 'index'])->name('users.index');
        Route::post('users', [UserController::class, 'store'])->name('users.store');
        Route::get('users/{user}', [UserController::class, 'show'])->whereUuid('user');
        Route::put('users/{user}', [UserController::class, 'update'])->whereUuid('user')->name('users.update');
        Route::post('users/{user}/revoke-all', [UserController::class, 'revoke'])->whereUuid('user');
        Route::get('roles', function () {
            Gate::authorize('roles.read');

            return ['data' => array_map(fn ($role) => ['code' => $role->value, 'permissions' => $role->permissions()], Role::cases())];
        });
        Route::get('audit-logs', AuditController::class);
        Route::get('prospects', [ProspectController::class, 'index']);
        Route::post('prospects', [ProspectController::class, 'store'])->name('prospects.store');
        Route::get('prospects/duplicates', [ProspectController::class, 'duplicates']);
        Route::get('prospects/{prospect}', [ProspectController::class, 'show'])->whereUuid('prospect');
        Route::put('prospects/{prospect}', [ProspectController::class, 'update'])->whereUuid('prospect')->name('prospects.update');
        Route::delete('prospects/{prospect}', [ProspectController::class, 'destroy'])->whereUuid('prospect');
        Route::post('prospects/{prospect}/assign', [ProspectController::class, 'assign'])->whereUuid('prospect')->name('prospects.assign');
        Route::post('prospects/{prospect}/stage', [ProspectController::class, 'stage'])->whereUuid('prospect')->name('prospects.stage');
        Route::post('prospects/{prospect}/archive', [ProspectController::class, 'archive'])->whereUuid('prospect')->name('prospects.archive');
        Route::post('prospects/{prospect}/contacts', [ProspectController::class, 'addContact'])->whereUuid('prospect')->name('contacts.store');
        Route::delete('prospects/{prospect}/contacts/{contactId}', [ProspectController::class, 'removeContact'])->whereUuid('prospect')->whereUuid('contactId');
        Route::get('prospect-sources', [MasterController::class, 'sources']);
        Route::post('prospect-sources', [MasterController::class, 'storeSource'])->name('masters.store.sources');
        Route::put('prospect-sources/{code}', [MasterController::class, 'updateSource'])->name('masters.update.sources');
        Route::get('industries', [MasterController::class, 'industries']);
        Route::post('industries', [MasterController::class, 'storeIndustry'])->name('masters.store.industries');
        Route::put('industries/{code}', [MasterController::class, 'updateIndustry'])->name('masters.update.industries');
        Route::get('lost-reasons', [MasterController::class, 'lostReasons']);
        Route::post('lost-reasons', [MasterController::class, 'storeReason'])->name('masters.store.reasons');
        Route::put('lost-reasons/{code}', [MasterController::class, 'updateReason'])->name('masters.update.reasons');
        Route::get('prospects/{prospect}/activities', [ActivityController::class, 'index'])->whereUuid('prospect');
        Route::post('prospects/{prospect}/activities', [ActivityController::class, 'store'])->whereUuid('prospect')->name('activities.log');
        Route::get('prospects/{prospect}/stage-history', [PipelineController::class, 'history'])->whereUuid('prospect');
        Route::get('pipeline', [PipelineController::class, 'board']);
        Route::post('prospects/{prospect}/follow-ups', [FollowUpController::class, 'store'])->whereUuid('prospect')->name('followups.store');
        Route::get('follow-ups', [FollowUpController::class, 'index']);
        Route::post('follow-ups/{followUp}/complete', [FollowUpController::class, 'complete'])->whereUuid('followUp')->name('followups.complete');
        Route::post('follow-ups/{followUp}/reschedule', [FollowUpController::class, 'reschedule'])->whereUuid('followUp')->name('followups.reschedule');
        Route::post('prospects/{prospect}/deals', [DealController::class, 'store'])->whereUuid('prospect')->name('deals.store');
        Route::get('prospects/{prospect}/deals', [DealController::class, 'index'])->whereUuid('prospect');
        Route::put('deals/{deal}', [DealController::class, 'update'])->whereUuid('deal')->name('deals.update');
        Route::post('deals/{deal}/won', [DealController::class, 'won'])->whereUuid('deal')->name('deals.won');
        Route::post('deals/{deal}/lost', [DealController::class, 'lost'])->whereUuid('deal')->name('deals.lost');
        Route::post('deals/{deal}/payment-status', [DealController::class, 'payment'])->whereUuid('deal')->name('deals.payment');
        Route::get('deals/{deal}/customer-candidates', [DealController::class, 'candidates'])->whereUuid('deal');
        Route::get('deals/{deal}/payment-history', [DealController::class, 'history'])->whereUuid('deal');
        Route::get('customers', [CustomerController::class, 'index']);
        Route::post('customers', [CustomerController::class, 'store'])->name('customers.store');
        Route::get('customers/{customer}', [CustomerController::class, 'show'])->whereUuid('customer');
        Route::put('customers/{customer}', [CustomerController::class, 'update'])->whereUuid('customer')->name('customers.update');
        Route::post('customers/{customer}/deals', [CustomerController::class, 'repeat'])->whereUuid('customer')->name('customers.repeat');
        Route::get('customers/{customer}/deals', [CustomerController::class, 'deals'])->whereUuid('customer');
        Route::post('imports', [ImportController::class, 'store'])->name('imports.store');
        Route::post('imports/{import}/batches', [ImportController::class, 'batches'])->whereUuid('import')->name('imports.batches');
        Route::post('imports/{import}/validate', [ImportController::class, 'validate'])->whereUuid('import')->name('imports.validate');
        Route::get('imports/{import}', [ImportController::class, 'show'])->whereUuid('import');
        Route::get('imports/{import}/rows', [ImportController::class, 'rows'])->whereUuid('import');
        Route::get('imports/{import}/errors.csv', [ImportController::class, 'errors'])->whereUuid('import');
        Route::post('imports/{import}/review', [ImportController::class, 'review'])->whereUuid('import')->name('imports.review');
        Route::post('imports/{import}/commit', [ImportController::class, 'commit'])->whereUuid('import')->name('imports.commit');
        Route::post('imports/{import}/cancel', [ImportController::class, 'cancel'])->whereUuid('import')->name('imports.cancel');
        Route::get('targets', [TargetController::class, 'index']);
        Route::post('targets', [TargetController::class, 'store'])->name('targets.store');
        Route::put('targets/{target}', [TargetController::class, 'update'])->whereUuid('target')->name('targets.update');
        Route::get('dashboard', [DashboardController::class, 'board'])->name('dashboard');
        Route::get('reports/performance', [DashboardController::class, 'performance'])->name('reports.performance');
        Route::get('reports/annual', [DashboardController::class, 'annual'])->name('reports.annual');
        Route::get('reports/annual-matrix', [DashboardController::class, 'annualMatrix'])->name('reports.annual_matrix');
        Route::post('exports/prospects', [ExportController::class, 'storeProspects'])->name('exports.store');
        Route::post('exports/performance', [ExportController::class, 'storePerformance'])->name('exports.performance');
        Route::get('exports/{export}', [ExportController::class, 'show'])->whereUuid('export');
        Route::get('exports/{export}/download', [ExportController::class, 'download'])->whereUuid('export');
        Route::post('archives/preview', [ArchiveController::class, 'preview'])->name('archives.preview');
        Route::post('archives', [ArchiveController::class, 'store'])->name('archives.store');
        Route::get('archives/{archive}', [ArchiveController::class, 'show'])->whereUuid('archive');
        Route::post('archives/{archive}/verify', [ArchiveController::class, 'verify'])->whereUuid('archive');
        Route::post('archives/{archive}/copy', [ArchiveController::class, 'copy'])->whereUuid('archive');
        Route::post('archives/{archive}/restore', [ArchiveController::class, 'restore'])->whereUuid('archive');
        Route::get('archives/{archive}/staging', [ArchiveController::class, 'staging'])->whereUuid('archive');
        Route::post('archives/{archive}/purge', [ArchiveController::class, 'purge'])->whereUuid('archive')->name('archives.purge');
    });
});
